[package]
name = "cmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = "0.9.2"
wasm-bindgen = "0.2.83"

[lib]
name = "cmark"
crate-type = ["cdylib"]